# Maps common user phrases to exact FAQ keys

FAQ_ALIASES = {

    # Account aliases
    "savings":                    "what is a savings account",
    "saving account":             "what is a savings account",
    "savings account":            "what is a savings account",
    "open account":               "how to open a bank account",
    "create account":             "how to open a bank account",
    "new account":                "how to open a bank account",
    "bank account opening":       "how to open a bank account",
    "minimum balance":            "what is minimum balance",
    "min balance":                "what is minimum balance",
    "zero balance":               "what is a zero balance account",
    "close account":              "how to close a bank account",
    "current account":            "what is a current account",

    # ATM aliases
    "atm":                        "what is atm",
    "atm machine":                "what is atm",
    "cash machine":               "what is atm",
    "withdraw cash":              "how to withdraw money from atm",
    "withdraw money":             "how to withdraw money from atm",
    "money withdrawal":           "how to withdraw money from atm",
    "check balance":              "how to check account balance",
    "balance check":              "how to check account balance",
    "account balance":            "how to check account balance",
    "balance enquiry":            "how to check account balance",
    "card blocked":               "atm card blocked",
    "atm blocked":                "atm card blocked",
    "blocked card":               "atm card blocked",
    "atm pin":                    "what is atm pin",
    "pin change":                 "what is atm pin",
    "forgot pin":                 "atm card blocked",

    # Card aliases
    "debit":                      "what is a debit card",
    "debit card":                 "what is a debit card",
    "credit":                     "what is a credit card",
    "credit card":                "what is a credit card",
    "difference debit credit":    "difference between debit and credit card",
    "debit vs credit":            "difference between debit and credit card",
    "block card":                 "how to block debit card",
    "lost card":                  "how to block debit card",
    "card stolen":                "how to block debit card",

    # Loan aliases
    "loan":                       "what is a bank loan",
    "bank loan":                  "what is a bank loan",
    "types of loan":              "what is a bank loan",
    "emi":                        "what is emi",
    "monthly installment":        "what is emi",
    "equated monthly":            "what is emi",
    "interest":                   "what is interest rate",
    "interest rate":              "what is interest rate",
    "bank interest":              "what is interest rate",
    "home loan":                  "what is home loan",
    "house loan":                 "what is home loan",
    "personal loan":              "what is personal loan",

    # Net banking / UPI aliases
    "net banking":                "what is net banking",
    "internet banking":           "what is net banking",
    "online banking":             "what is net banking",
    "upi":                        "what is upi",
    "gpay":                       "what is upi",
    "phonepe":                    "what is upi",
    "google pay":                 "what is upi",
    "paytm":                      "what is upi",
    "transfer money":             "how to transfer money online",
    "send money":                 "how to transfer money online",
    "online transfer":            "how to transfer money online",
    "money transfer":             "how to transfer money online",
    "ifsc":                       "what is ifsc code",
    "ifsc code":                  "what is ifsc code",
    "neft":                       "what is neft",
    "fund transfer":              "how to transfer money online",

    # FD / Investment aliases
    "fd":                         "what is fixed deposit",
    "fixed deposit":              "what is fixed deposit",
    "fixed deposit account":      "what is fixed deposit",
    "rd":                         "what is recurring deposit",
    "recurring deposit":          "what is recurring deposit",

    # Security / KYC aliases
    "kyc":                        "what is kyc",
    "know your customer":         "what is kyc",
    "kyc documents":              "what is kyc",
    "account safe":               "how to keep account safe",
    "bank safety":                "how to keep account safe",
    "secure account":             "how to keep account safe",
    "otp":                        "what is otp",
    "one time password":          "what is otp",
    "fraud":                      "what to do if fraud transaction",
    "fraudulent transaction":     "what to do if fraud transaction",
    "unauthorized transaction":   "what to do if fraud transaction",
    "scam":                       "what to do if fraud transaction",
}